### ISSUE TITLE
Could not install and use

### ISSUE THREAD

**Issue by OpenMindAmir** [ssshojaei/aparat_dl#1]
I can not install or use it 

when i want to run:
`cd ~/.apps/aparat_dl;npm i;`

it returns:

```cd ~/.apps/aparat_dl; npm i
loadDep:puppeteer → resol ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine puppeteer@2.1.1: wanted: {"node":">=8.16.0"} (current: {"node":"4.2.loadDep:puppeteer → 304   ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine download@7.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","nploadDep:puppeteer → 304   ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine inquirer@7.1.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6"loadDep:pify → cache      ▌ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine p-event@2.3.1: wanted: {"node":">=6"} (current: {"node":"4.2.6","npmloadDep:pify → 200        ▐ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine file-type@8.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","nloadDep:chalk → fetchName ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine string-width@4.2.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine strip-ansi@6.0.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","loadDep:strip-ansi → 304  ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine cli-cursor@3.1.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine ansi-escapes@4.3.1: wanted: {"node":">=8"} (current: {"node":"4.2.6"loadDep:strip-ansi → get  ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine figures@3.2.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","npmloadDep:strip-ansi → mapT ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine chalk@3.0.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","npm":loadDep:type-fest → 304   ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine type-fest@0.11.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","loadDep:supports-color →  ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine ansi-styles@4.2.1: wanted: {"node":">=8"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine supports-color@7.1.0: wanted: {"node":">=8"} (current: {"node":"4.2.loadDep:color-convert → 3 ▐ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine color-convert@2.0.1: wanted: {"node":">=7.0.0"} (current: {"node":"4loadDep:has-flag → 304    ▐ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine has-flag@4.0.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","nploadDep:restore-cursor →  ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine restore-cursor@3.1.0: wanted: {"node":">=8"} (current: {"node":"4.2.loadDep:signal-exit → net ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine onetime@5.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","npmloadDep:mimic-fn → 304    ▐ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine mimic-fn@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","nploadDep:tslib → afterAdd  ▀ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine is-fullwidth-code-point@3.0.0: wanted: {"node":">=8"} (current: {"noloadDep:is-fullwidth-code ▌ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine ansi-regex@5.0.0: wanted: {"node":">=8"} (current: {"node":"4.2.6","loadDep:ws → resolveWithN ▀ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine https-proxy-agent@4.0.0: wanted: {"node":">= 6.0.0"} (current: {"nodnpm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
loadDep:agent-base → 304  ▀ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine agent-base@5.1.1: wanted: {"node":">= 6.0.0"} (current: {"node":"4.2
> puppeteer@2.1.1 install /home/username/.apps/aparat_dl/node_modules/puppeteer
> node install.js

/home/username/.apps/aparat_dl/node_modules/puppeteer/install.js:80
  return Promise.all([...cleanupOldVersions, generateProtocolTypesIfNecessary(true /* updated */)]);
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
aparat_dl@1.0.2 /home/username/.apps/aparat_dl
├─┬ cli-progress@3.6.0 
│ ├── colors@1.4.0 
│ └─┬ string-width@2.1.1 
│   ├── is-fullwidth-code-point@2.0.0 
│   └─┬ strip-ansi@4.0.0 
│     └── ansi-regex@3.0.0 
├─┬ download@7.1.0 
│ ├─┬ archive-type@4.0.0 
│ │ └── file-type@4.4.0 
│ ├─┬ caw@2.0.1 
│ │ ├─┬ get-proxy@2.1.0 
│ │ │ └─┬ npm-conf@1.1.3 
│ │ │   └─┬ config-chain@1.1.12 
│ │ │     ├── ini@1.3.5 
│ │ │     └── proto-list@1.2.4 
│ │ ├─┬ isurl@1.0.0 
│ │ │ ├─┬ has-to-string-tag-x@1.4.1 
│ │ │ │ └── has-symbol-support-x@1.4.2 
│ │ │ └── is-object@1.0.1 
│ │ ├── tunnel-agent@0.6.0 
│ │ └── url-to-options@1.0.1 
│ ├─┬ content-disposition@0.5.3 
│ │ └── safe-buffer@5.1.2 
│ ├─┬ decompress@4.2.0 
│ │ ├─┬ decompress-tar@4.1.1 
│ │ │ ├── file-type@5.2.0 
│ │ │ ├── is-stream@1.1.0 
│ │ │ └─┬ tar-stream@1.6.2 
│ │ │   ├── bl@1.2.2 
│ │ │   ├─┬ buffer-alloc@1.2.0 
│ │ │   │ ├── buffer-alloc-unsafe@1.1.0 
│ │ │   │ └── buffer-fill@1.0.0 
│ │ │   ├─┬ end-of-stream@1.4.4 
│ │ │   │ └─┬ once@1.4.0 
│ │ │   │   └── wrappy@1.0.2 
│ │ │   ├── fs-constants@1.0.0 
│ │ │   ├─┬ readable-stream@2.3.7 
│ │ │   │ ├── core-util-is@1.0.2 
│ │ │   │ ├── isarray@1.0.0 
│ │ │   │ ├── process-nextick-args@2.0.1 
│ │ │   │ ├── safe-buffer@5.1.2 
│ │ │   │ ├─┬ string_decoder@1.1.1 
│ │ │   │ │ └── safe-buffer@5.1.2 
│ │ │   │ └── util-deprecate@1.0.2 
│ │ │   ├── to-buffer@1.1.1 
│ │ │   └── xtend@4.0.2 
│ │ ├─┬ decompress-tarbz2@4.1.1 
│ │ │ ├── file-type@6.2.0 
│ │ │ ├─┬ seek-bzip@1.0.5 
│ │ │ │ └─┬ commander@2.8.1 
│ │ │ │   └── graceful-readlink@1.0.1 
│ │ │ └─┬ unbzip2-stream@1.3.3 
│ │ │   └─┬ buffer@5.5.0 
│ │ │     ├── base64-js@1.3.1 
│ │ │     └── ieee754@1.1.13 
│ │ ├─┬ decompress-targz@4.1.1 
│ │ │ └── file-type@5.2.0 
│ │ ├─┬ decompress-unzip@4.0.1 
│ │ │ ├── file-type@3.9.0 
│ │ │ ├─┬ get-stream@2.3.1 
│ │ │ │ ├── object-assign@4.1.1 
│ │ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │ │   └── pinkie@2.0.4 
│ │ │ ├── pify@2.3.0 
│ │ │ └─┬ yauzl@2.10.0 
│ │ │   ├── buffer-crc32@0.2.13 
│ │ │   └─┬ fd-slicer@1.1.0 
│ │ │     └── pend@1.2.0 
│ │ ├── graceful-fs@4.2.3 
│ │ ├── pify@2.3.0 
│ │ └─┬ strip-dirs@2.1.0 
│ │   └── is-natural-number@4.0.1 
│ ├─┬ ext-name@5.0.0 
│ │ ├─┬ ext-list@2.2.2 
│ │ │ └── mime-db@1.43.0 
│ │ └─┬ sort-keys-length@1.0.1 
│ │   └─┬ sort-keys@1.1.2 
│ │     └── is-plain-obj@1.1.0 
│ ├── file-type@8.1.0 
│ ├─┬ filenamify@2.1.0 
│ │ ├── filename-reserved-regex@2.0.0 
│ │ ├── strip-outer@1.0.1 
│ │ └── trim-repeated@1.0.0 
│ ├── get-stream@3.0.0 
│ ├─┬ got@8.3.2 
│ │ ├── @sindresorhus/is@0.7.0 
│ │ ├─┬ cacheable-request@2.1.4 
│ │ │ ├── clone-response@1.0.2 
│ │ │ ├── http-cache-semantics@3.8.1 
│ │ │ ├─┬ keyv@3.0.0 
│ │ │ │ └── json-buffer@3.0.0 
│ │ │ ├── lowercase-keys@1.0.0 
│ │ │ ├─┬ normalize-url@2.0.1 
│ │ │ │ ├─┬ query-string@5.1.1 
│ │ │ │ │ ├── decode-uri-component@0.2.0 
│ │ │ │ │ └── strict-uri-encode@1.1.0 
│ │ │ │ └── sort-keys@2.0.0 
│ │ │ └── responselike@1.0.2 
│ │ ├── decompress-response@3.3.0 
│ │ ├── duplexer3@0.1.4 
│ │ ├─┬ into-stream@3.1.0 
│ │ │ ├─┬ from2@2.3.0 
│ │ │ │ └── inherits@2.0.4 
│ │ │ └── p-is-promise@1.1.0 
│ │ ├── is-retry-allowed@1.2.0 
│ │ ├── lowercase-keys@1.0.1 
│ │ ├── mimic-response@1.0.1 
│ │ ├── p-cancelable@0.4.1 
│ │ ├─┬ p-timeout@2.0.1 
│ │ │ └── p-finally@1.0.0 
│ │ ├── safe-buffer@5.2.0 
│ │ ├── timed-out@4.0.1 
│ │ └─┬ url-parse-lax@3.0.0 
│ │   └── prepend-http@2.0.0 
│ ├── make-dir@1.3.0 
│ ├── p-event@2.3.1 
│ └── pify@3.0.0 
└─┬ inquirer@7.1.0 
  ├─┬ ansi-escapes@4.3.1 
  │ └── type-fest@0.11.0 
  ├─┬ chalk@3.0.0 
  │ ├─┬ ansi-styles@4.2.1 
  │ │ ├── @types/color-name@1.1.1 
  │ │ └─┬ color-convert@2.0.1 
  │ │   └── color-name@1.1.4 
  │ └─┬ supports-color@7.1.0 
  │   └── has-flag@4.0.0 
  ├─┬ cli-cursor@3.1.0 
  │ └─┬ restore-cursor@3.1.0 
  │   ├─┬ onetime@5.1.0 
  │   │ └── mimic-fn@2.1.0 
  │   └── signal-exit@3.0.3 
  ├── cli-width@2.2.0 
  ├─┬ external-editor@3.1.0 
  │ ├── chardet@0.7.0 
  │ ├─┬ iconv-lite@0.4.24 
  │ │ └── safer-buffer@2.1.2 
  │ └─┬ tmp@0.0.33 
  │   └── os-tmpdir@1.0.2 
  ├─┬ figures@3.2.0 
  │ └── escape-string-regexp@1.0.5 
  ├── lodash@4.17.15 
  ├── mute-stream@0.0.8 
  ├─┬ run-async@2.4.0 
  │ └── is-promise@2.1.0 
  ├─┬ rxjs@6.5.4 
  │ └── tslib@1.11.1 
  ├─┬ string-width@4.2.0 
  │ ├── emoji-regex@8.0.0 
  │ └── is-fullwidth-code-point@3.0.0 
  ├─┬ strip-ansi@6.0.0 
  │ └── ansi-regex@5.0.0 
  └── through@2.3.8 

npm WARN aparat_dl@1.0.2 license should be a valid SPDX license expression
npm ERR! Linux 4.15.0-91-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.1.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/.apps/aparat_dl/npm-debug.log```

And when I want to download a video:

```/home/mwxgaf/.apps/aparat_dl/index.js:9
let bar, download_bar, url, path
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by ssshojaei** [comment]
Thanks for creating this issue
the project was rewritten for easier use
